definitions:
  serializer.Response:
    properties:
      data: {}
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /sdwebuiapi/img2img:
    post:
      description: 图生图
      parameters:
      - description: 图片url
        in: formData
        name: original_url
        required: true
        type: string
      - description: mask_url 遮罩层 oss 路径
        in: formData
        name: mask_url
        required: true
        type: string
      - description: prompts 文字关键词
        in: formData
        name: prompts
        type: string
      - description: model_id 风格ID
        in: formData
        name: model_id
        required: true
        type: integer
      - description: size 0或4 跟随原图尺寸 1 3:4竖 2 4:3横 3 1:1方
        in: formData
        name: size
        required: true
        type: integer
      - description: denoising_strength 相似度 1~0
        in: formData
        name: denoising_strength
        type: boolean
      - description: inpainting_fill 重绘 1 不重绘0
        in: formData
        name: inpainting_fill
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 图生图
      tags:
      - sdapi相关
  /sdwebuiapi/txt2img:
    post:
      description: 文生图
      parameters:
      - description: prompts 文字关键词
        in: formData
        name: prompts
        type: string
      - description: size 1 3:4竖 2 4:3横 3 1:1方
        in: formData
        name: size
        required: true
        type: integer
      - description: model_id 风格ID
        in: formData
        name: model_id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/serializer.Response'
      summary: 文生图
      tags:
      - sdapi相关
swagger: "2.0"
